version: '3.8'

services:
  # Main application service
  evault-law:
    build: .
    container_name: evault-law
    ports:
      - "3000:3000"  # Frontend server
      - "8545:8545"  # Hardhat node
    volumes:
      - ./backend/.env:/app/backend/.env
      - ./frontend:/app/frontend
      - ./backend/contracts:/app/backend/contracts
      - blockchain_data:/app/.hardhat
    environment:
      - NODE_ENV=production
      - ADMIN_ADDRESS=0x13591389EE06948758541b38547a37FB9483F2f4
      - FILEBASE_BUCKET=${FILEBASE_BUCKET:-evault-law}
      - FILEBASE_API_KEY=${FILEBASE_API_KEY}
    command: >
      sh -c "npm run node & sleep 5 && 
             npm run deploy-admin && 
             npm run update-frontend && 
             npm run start"
    restart: unless-stopped
    depends_on:
      - filebase-proxy

  # Filebase IPFS proxy service
  filebase-proxy:
    build:
      context: ./filebase-proxy
      dockerfile: Dockerfile
    container_name: filebase-proxy
    ports:
      - "3001:3001"  # Filebase proxy API
    environment:
      - PORT=3001
      - FILEBASE_API_KEY=${FILEBASE_API_KEY}
      - FILEBASE_BUCKET=${FILEBASE_BUCKET:-evault-law}
    volumes:
      - ./filebase-proxy:/app
    restart: unless-stopped

  # Local IPFS node for development and testing
  ipfs:
    image: ipfs/kubo:latest
    container_name: ipfs
    ports:
      - "5001:5001"  # API
      - "8080:8080"  # Gateway
    volumes:
      - ipfs_data:/data/ipfs
    restart: unless-stopped

volumes:
  ipfs_data:
  blockchain_data: